name: Mirroring

on:
  push:

env:
  MIRROR_URL: "git@github.com:EpitechPGE45-2025/G-CLO-910-PAR-9-1-cloudnative-13.git"

jobs:
  push_to_mirror:
    name: Mirorring
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check mirorring
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
